# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa95990df7ac6535f5f460b774391eb062e2e25b3dafcbf12f9dc63cb8cb02ef0099f56fcd22229456f22d5f0e5035188a66c475fb2539174397c9ccd0c3ea9b

test:
  secret_key_base: 1742c7469c27108de8c927b1ebd5d08c0cfee7bb8f68382830876fc8ba942ea1374bbbaedac8a738b1f7e061fd5c754d04906c5edd1a5688bf1d210e8c922f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
